package com.icm.bean;
// Generated 3 Feb, 2020 5:17:24 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", schema = "public")
public class Authority implements java.io.Serializable {

	private int authorityId;
	private String authorityType;
	private Character authorityIdentity;
	private Set<UserAuthority> userAuthorities = new HashSet<UserAuthority>(0);

	public Authority() {
	}

	public Authority(int authorityId) {
		this.authorityId = authorityId;
	}

	public Authority(int authorityId, String authorityType, Character authorityIdentity,
			Set<UserAuthority> userAuthorities) {
		this.authorityId = authorityId;
		this.authorityType = authorityType;
		this.authorityIdentity = authorityIdentity;
		this.userAuthorities = userAuthorities;
	}

	@Id

	@Column(name = "AUTHORITY_ID", unique = true, nullable = false)
	public int getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(int authorityId) {
		this.authorityId = authorityId;
	}

	@Column(name = "AUTHORITY_TYPE")
	public String getAuthorityType() {
		return this.authorityType;
	}

	public void setAuthorityType(String authorityType) {
		this.authorityType = authorityType;
	}

	@Column(name = "AUTHORITY_IDENTITY", length = 1)
	public Character getAuthorityIdentity() {
		return this.authorityIdentity;
	}

	public void setAuthorityIdentity(Character authorityIdentity) {
		this.authorityIdentity = authorityIdentity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authority")
	public Set<UserAuthority> getUserAuthorities() {
		return this.userAuthorities;
	}

	public void setUserAuthorities(Set<UserAuthority> userAuthorities) {
		this.userAuthorities = userAuthorities;
	}

}
