package com.icm.bean;
// Generated 3 Feb, 2020 5:17:24 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAuthorityId generated by hbm2java
 */
@Embeddable
public class UserAuthorityId implements java.io.Serializable {

	private int userId;
	private int authorityId;

	public UserAuthorityId() {
	}

	public UserAuthorityId(int userId, int authorityId) {
		this.userId = userId;
		this.authorityId = authorityId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "AUTHORITY_ID", nullable = false)
	public int getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(int authorityId) {
		this.authorityId = authorityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAuthorityId))
			return false;
		UserAuthorityId castOther = (UserAuthorityId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getAuthorityId() == castOther.getAuthorityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getAuthorityId();
		return result;
	}

}
