package com.icm.bean;
// Generated 3 Feb, 2020 5:17:24 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAuthority generated by hbm2java
 */
@Entity
@Table(name = "user_authority", schema = "public")
public class UserAuthority implements java.io.Serializable {

	private UserAuthorityId id;
	private Authority authority;
	private Users users;
	private String authorityIdentity;

	public UserAuthority() {
	}

	public UserAuthority(UserAuthorityId id, Authority authority, Users users) {
		this.id = id;
		this.authority = authority;
		this.users = users;
	}

	public UserAuthority(UserAuthorityId id, Authority authority, Users users, String authorityIdentity) {
		this.id = id;
		this.authority = authority;
		this.users = users;
		this.authorityIdentity = authorityIdentity;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "authorityId", column = @Column(name = "AUTHORITY_ID", nullable = false)) })
	public UserAuthorityId getId() {
		return this.id;
	}

	public void setId(UserAuthorityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTHORITY_ID", nullable = false, insertable = false, updatable = false)
	public Authority getAuthority() {
		return this.authority;
	}

	public void setAuthority(Authority authority) {
		this.authority = authority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "AUTHORITY_IDENTITY")
	public String getAuthorityIdentity() {
		return this.authorityIdentity;
	}

	public void setAuthorityIdentity(String authorityIdentity) {
		this.authorityIdentity = authorityIdentity;
	}

}
